Repository WattRex/System-Tools, pull requests merged in 2023-08, with the labels that each got.

#1 Sys conf and CI/CD working
  .git_archival.txt
  .gitattributes
  .github/actions/build-package/action.yml
  .github/actions/build-package/get_version.py
  .github/actions/setup-python/action.yml
  .github/workflows/build_python_package.yml
  .github/workflows/deploy_sys_2_development.yml
  .gitignore
  .vscode/.pylintrc
  .vscode/settings.json
  code/sys_conf/LICENSE
  code/sys_conf/MANIFEST.in
  code/sys_conf/README.md
  code/sys_conf/pyproject.toml
  code/sys_conf/requirements.txt
  code/sys_conf/src/system_config_tool/__init__.py
  code/sys_conf/src/system_config_tool/sys_conf.py
  code/sys_conf/tests/test.py
Labels: good first issue

#4 Relative paths removed from deployment
  .github/workflows/build_python_package.yml
  .github/workflows/deploy_sys_2_development.yml
Labels: enhancement

#6 Update sys_log module to work with modules properly
  code/sys_log/src/system_logger_tool/__init__.py
  code/sys_log/src/system_logger_tool/sys_log.py
Labels: enhancement

#9 Sys Shd Requirements updated
  code/sys_shd/requirements.txt
Labels: enhancement

#11 Sys shd
  .vscode/.pylintrc
  LICENSE.txt
  code/sys_conf/LICENSE.txt
  code/sys_log/LICENSE.txt
  code/sys_shd/LICENSE.txt
  code/sys_shd/src/system_shared_tool/sys_shd.py
Labels: bug

#12 Update action.yml, deleting extra code folder in pylint
  .github/actions/build-package/action.yml
Labels: bug

#13 Update pytest to run only files that start with test in the tests folder
  .github/actions/build-package/action.yml
Labels: enhancement

#8 Add example_lvl_config.yaml
  .vscode/.pylintrc
  .vscode/settings.json
  code/sys_log/MANIFEST.in
  code/sys_log/requirements.txt
  code/sys_log/src/system_logger_tool/__init__.py
  code/sys_log/src/system_logger_tool/example_lvl_config.yaml
  code/sys_log/src/system_logger_tool/logginConfig.conf
  code/sys_log/src/system_logger_tool/sys_log.py
  code/sys_log/tests/context.py
  code/sys_log/tests/log_config.yaml
  code/sys_log/tests/support_code.py
  code/sys_log/tests/test.py
  code/sys_log/tests/test_sys_log.py
Labels: documentation
